digest: 24b0c42f
name: dataset
profile: '{"features_shape": [112, 4], "features_size": 448, "features_nbytes": 3584,
  "targets_shape": [112], "targets_size": 112, "targets_nbytes": 896}'
schema: '{"mlflow_tensorspec": {"features": "[{\"type\": \"tensor\", \"tensor-spec\":
  {\"dtype\": \"float64\", \"shape\": [-1, 4]}}]", "targets": "[{\"type\": \"tensor\",
  \"tensor-spec\": {\"dtype\": \"int64\", \"shape\": [-1]}}]"}}'
source: '{"tags": {"mlflow.user": "root", "mlflow.source.name": "test.py", "mlflow.source.type":
  "LOCAL"}}'
source_type: code
